### ISSUE TITLE
HoC cleanup

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-fela#1]
The code is still kind of dirty and even contains duplicate code parts which we should get rid of as soon as possible. Refactoring should also come with initial testing.

**Comment by johanneslumpe** [comment]
Should this really be in `render`?

https://github.com/rofrischmann/react-fela/blob/master/modules/helpers/bindStateToFela.js#L17

**Comment by rofrischmann** [comment]
Actually it'd be enough to do it if the state changes. As said this is just a quick working version.

**Comment by johanneslumpe** [comment]
@rofrischmann I will send a PR for this soon.

**Comment by johanneslumpe** [comment]
https://github.com/rofrischmann/react-fela/pull/4
