### ISSUE TITLE
props not passed to render rules

### ISSUE THREAD

**Issue by at0g** [rofrischmann/react-fela#10]
I'm experiencing some weird behaviour where the style rule is being called 3 times (the first two times with no props).

```
import React from 'react';
import { connect } from 'react-fela';

const foo = props => {
	// expecting this to ALWAYS log ["foo"]
	console.log(Object.keys(props));
	return {
		color: 'red'
	};
};

export default connect(props => renderer => {
	return {
		foo: renderer.renderRule(foo, {
			foo: 'foo'
		})
	};
})(
	({ styles }) => (
		<pre>{ JSON.stringify(styles, null, 4) }</pre>
	)
)
```

With the example above, I see the following in console:

```
[]
[]
["foo"]
```

Why are there 2 calls to the rule with an empty object?

**Comment by rofrischmann** [comment]
That's actually a "issue" with Fela, not with the bindings. But it not really is an issue. Fela always initially renders each rule without props to get the static style which every variation shares. Afterwards the rule is rendered with the passed `props` and gets diffed with the static styles to render the minimum CSS markup. Still there should only be a single static call, not two. I might investigate later!

**Comment by at0g** [comment]
Thanks for the detailed response Robin, appreciate you taking the time to explain the how and why.
