### ISSUE TITLE
Dynamic rules are not compatible with React Addon TransitionGroup

### ISSUE THREAD

**Issue by hufeihxw** [rofrischmann/react-fela#12]
It's not really a Fela issue, I just thought recording it here might be good

Fela renders dynamic rules to combined classnames

[React animation, custom classes](https://facebook.github.io/react/docs/animation.html#custom-classes)

    const rule = props => ({
      fontSize: '15px',
      color: props.color, //this one will be used for transition
      lineHeight: 1.5
    })
    
    ends up something like 'c1 c1-[hash]`

Its the right way to reduce css size, but currently its not compatible with ReactCssTransitionGroup

[combined classnames do not work](https://github.com/facebook/react/issues/2680)

I think currently the only way to use dynamic rules with ReactCssTransitionGroup is 

    const style = {
      fontSize: '15px',
      color: props.color,
      lineHeight: 1.5
    }

    const rule = props => style

This will cause un-optimized classes, but what can you do until React fixes that issue

maybe if Fela can detect a rule without static values, we can do this

    const rule = props => ({
      color: props.color
    })
    //if fela can render this into  'c1-[hash]`
    //then I can split the rule to a dynamic one and a static one, only use the dynamic part with css transition group

     const ruleStatic = props => ({
      fontSize: '15px',
      lineHeight: 1.5
    })
    const dynamicRule = props => ({
      color: props.color
    }) //c1-hash   use this one in ReactCSSTransitionGroup

**Comment by rofrischmann** [comment]
I am about to add another change that renders pure dynamic rules without a static rule set. This is what would help you right?

**Comment by rofrischmann** [comment]
This should be possible using the newest version of Fela which can single dynamic classNames as well.
