### ISSUE TITLE
Peer dependency of fela ^1.2.0 - Bump to ^3.0.0?

### ISSUE THREAD

**Issue by Brian-Gaffney** [rofrischmann/react-fela#14]
React fela has a peer dependency of `"fela": "^1.2.0"`.
It seems to work fine with fela 3.0.0 though.

Any reason the peer depencency can't be bumped to `"fela": "^3.0.0"`?

**Comment by rofrischmann** [comment]
just updated the deps:P Was not updating for a long time, but react-fela should always be compatible with fela :)

**Comment by rofrischmann** [comment]
Btw. do you have a Twitter account? Would like to mention u the next time :)

**Comment by Brian-Gaffney** [comment]
Hey Robin.
I don't have Twitter, but that's ok, no need for the mention.
Happy to contribute regardless, thanks for making fela in the first place!
