### ISSUE TITLE
pretty developer friendly classnames

### ISSUE THREAD

**Issue by einarlove** [rofrischmann/react-fela#8]
Do you have any plans to implement a way to have more developer friendly classnames like in your previous project [react-look](https://github.com/rofrischmann/react-look)?

Example `{component}-{className}-{id}` => `ListItem-heading-c14--gn3w1`

**Comment by rofrischmann** [comment]
Right now the architecture does not simply support extra plugin meta data, but I am sure to be able to add this for future updates. Right now I am just about to ship the React Native version as soon as tests pass successfully. Feel free to open a feature request issue at the main Fela repository though :)

**Comment by Brian-Gaffney** [comment]
Fela 3.0.1 adds a config that can output more readable selectors.

See the `prettySelectors` option of the renderer configuration. http://fela.js.org/docs/advanced/RendererConfiguration.html

**Comment by rofrischmann** [comment]
@einarlove I will create a new issue on the fela repo for the specific component use case =) Going to close the issue board for fela related packages to maintain them all in one.
