### ISSUE TITLE
react-fela creates new styles on every render even if no props change

### ISSUE THREAD

**Issue by einarlove** [rofrischmann/react-fela#9]
react-fela will [recreate all the styles](https://github.com/rofrischmann/react-fela/blob/3311a562d50f2b5520bbc12b163636f09be28bcb/modules/components/connect.js#L17) on each render even when the props have not changed if I'm not mistaken.
Trying to do a `shallowEqual(prevProps, props)` will not help either since `prevProps.styles !== props.styles` because `props => styles` creates a new object every time.

Am I overreacting or might this be a performance issue?

**Comment by einarlove** [comment]
I found the issue. I was using [fela-styles-connector](https://github.com/dustin-H/fela-styles-connector) which passes all the props to the style functions.

Shame to stop using that utility since it solves the hassels of the react-fela connector ☹️

**Comment by rofrischmann** [comment]
May I close this one? Seems like you found the problem. Though you might add a pull request at fela-styles-connector?

**Comment by einarlove** [comment]
Sure
